import './blocks/banner-1';
import './blocks/headmaster-1';
import './blocks/features-1'
import './blocks/section-header-1';
import './blocks/gallery-1';
import './blocks/timeline-tab-1';
import './blocks/event-1';
import './blocks/about-1';
import './blocks/priority-section-1';
import './blocks/location-section-1';
import './blocks/honorable-teachers-1';
import './blocks/image-slider-1';
import './blocks/lab-section-1';
import './blocks/cta-1';
import './blocks/image-box-1';
import './blocks/mission-1';
